### ISSUE TITLE
Semantic Elements instead of Div

### ISSUE THREAD

**Issue by hamidazim321** [dvcorreia1984/portfolio#5]
Try using semantic elements like **main**, **section**, **figure** etc.. that is suitable for the type of data you put in it instead of Divs for everything. Semantic elements improve SEO search engine rankings for your web page and make it more visible on the web together with other benefits. It's a good practice to understand how to use them early on since they will be required later in more significant projects. Other than that, I think your code is quite organised, clean and easy to read. Keep up the good work. Cheers.

**Comment by dvcorreia1984** [comment]
Appreciate your comments.


Op Do. 8 Jun. 2023 om 09:48 het Hamid Azim Shah ***@***.***>
geskryf:
